- hosts: redis
  sudo: yes
  user: ubuntu
  gather_facts: False
  pre_tasks:
  - name: Install python2
    raw: sudo apt-get -y install python-simplejson

  - name: Clear directory
    raw: rm -rf /home/redis-3.2.5

  tasks:

  - name: Install build essentials
    apt: pkg=build-essential state=installed update_cache=yes

  - name: Install tcl
    apt: pkg=tcl state=installed update_cache=yes

  - name: Get redis
    get_url:
      url: http://download.redis.io/releases/redis-3.2.5.tar.gz
      dest: /home/

  - name: Untar
    unarchive: src=/home/redis-3.2.5.tar.gz dest=/home/ creates=yes remote_src=yes

  - name: Run makefile
    shell: chdir=/home/redis-3.2.5 make

  - name: Copy redis configuration file
    template: src=redis.conf dest=/home/redis-3.2.5/redis.conf

  - name: Copy redis service
    template: src=redis.service dest=/etc/systemd/system/redis.service

  - name: Start redis service
    service: name=redis state=restarted
