- hosts: redis
  sudo: yes
  user: ubuntu
  gather_facts: False
  pre_tasks:

  - name: Updates
    raw: apt-get update

  - name: Install python2
    raw: sudo apt-get -y install python-simplejson

  - name: Clear directory
    raw: rm -rf /home/redis-3.2.5

  - name: Clear Application
    raw: rm -rf /home/graph

  tasks:

  - name: Install NodeJS
    apt: pkg=nodejs state=installed update_cache=yes

  - name: Install npm
    apt: pkg=npm state=installed update_cache=yes

  - name: Install git
    apt: pkg=git state=installed update_cache=yes

  - name: Install build essentials
    apt: pkg=build-essential state=installed update_cache=yes

  - name: Install tcl
    apt: pkg=tcl state=installed update_cache=yes

  - name: Resolving node and nodejs
    command: ln -s /usr/bin/nodejs /usr/bin/node creates=/usr/bin/node

  - name: Install forever
    shell: npm install forever -g

  - name: Copying Server Software
    git: repo=https://github.com/subodh-dharma/DevOps-M3.git dest=/home/graph version=redis

  - name: Creating Logs file setup - graph plotter
    file: path=/home/graph/logs state=directory

  - name: Creating Logs file setup - autoscaler
    file: path=/home/autoscaler/logs state=directory

  - name: Installing Server Software
    shell: npm --prefix /home/graph install

  - name: Stop all forever processes
    raw: forever stopall

  - name: Get redis
    get_url:
      url: http://download.redis.io/releases/redis-3.2.5.tar.gz
      dest: /home/

  - name: Untar
    shell: chdir=/home tar xzf redis-3.2.5.tar.gz

  - name: Run makefile
    shell: chdir=/home/redis-3.2.5 make

  - name: Copy redis configuration file
    template: src=redis.conf dest=/home/redis-3.2.5/redis.conf

  - name: Copy redis service
    template: src=redis.service dest=/etc/systemd/system/redis.service

  - name: Start redis service
    service: name=redis state=restarted

  - name: Starting Web Server
    command: forever --workingDir /home/graph start -l /home/graph/logs/forever.log -o /home/graph/logs/out.log -e /home/graph/logs/err.log /home/graph/plotgraph.js {{hostvars['redis']['ansible_host']}}

  - name: Starting Auto-Scaler
    command: forever start -l /home/autoscaler/logs/forever.log -o /home/autoscaler/logs/out.log -e /home/autoscaler/logs/err.log autoscaler.js {{hostvars['redis']['ansible_host']}}
