- hosts: redis
  sudo: yes
  user: ubuntu
  gather_facts: False
  pre_tasks:
  - name: Install python2
    raw: sudo apt-get -y install python-simplejson

  - name: Clear directory
    raw: rm -rf /home/redis

  tasks:

  - name: Install build essentials
    apt: pkg=build-essential state=installed update_cache=yes

  - name: Install tcl
    apt: pkg=tcl state=installed update_cache=yes

  - name: Install redis-server
    apt: pkg=redis-server state=installed update_cache=yes



  # - name: Download redis source code
  #   get_url:
  #     url: http://download.redis.io/redis-stable.tar.gz
  #     dest: /tmp/redis-stable.tar.gz

  # - name: Remove prev redis directory
  #   file: path=/tmp/redis-stable state=absent

  # - name: Extract redis
  #   unarchive: src=/tmp/redis-stable.tar.gz dest=/tmp/ remote_src=yes creates=yes

  # - name: Run makefile
  #   shell: chdir=/tmp/redis-stable make

  # - name: Run install binaries
  #   shell: chdir=/tmp/redis-stable make install

  # - name: Create configuration directory
  #   file: path=/etc/redis state=directory

  - name: Copy redis configuration file
    template: src=redis.conf dest=/etc/redis/redis.conf

  # - name: Create data directory
  #   file: path=/var/lib/redis state=directory mode=0770

  # - name: Copy redis service
  #   template: src=redis.service dest=/etc/systemd/system/redis.service

  - name: Start redis service
    service: name=redis-server state=restarted
