- hosts: all
  sudo: yes
  user: ubuntu
  pre-tasks:
  - name: Install python2
    apt: pkg=python-simplejson state=installed update_cache=yes
  
  tasks:

  - name: Install NodeJS
    apt: pkg=nodejs state=installed update_cache=yes

  - name: Install npm
    apt: pkg=npm state=installed update_cache=yes

  - name: Install git
    apt: pkg=git state=installed update_cache=yes
  
  - name: Resolving node and nodejs
    command: ln -s /usr/bin/nodejs /usr/bin/node creates=/usr/bin/node

  - name: Install forever
    shell: npm install forever -g

  - name: Create Project folder
    file: path=/home/production state=directory

  - name: Copying Server Software
    git: repo=https://github.com/subodh-dharma/DevOps-M3.git dest=/home/production

  - name: Installing Server Software
    shell: npm --prefix /home/production install

  - name: Starting Web Server
    command: forever start /home/production/main.js
