- hosts: production
  sudo: yes
  user: ubuntu
  gather_facts: False
  pre_tasks:
  - name: Install python2
    raw: sudo apt-get -y install python-simplejson

  - name: Clear directory
    raw: rm -rf /home/production

  tasks:

  - name: Install NodeJS
    apt: pkg=nodejs state=installed update_cache=yes

  - name: Install npm
    apt: pkg=npm state=installed update_cache=yes

  - name: Install git
    apt: pkg=git state=installed update_cache=yes

  - name: Resolving node and nodejs
    command: ln -s /usr/bin/nodejs /usr/bin/node creates=/usr/bin/node

  - name: Install forever
    shell: npm install forever -g

  - name: Create Project folder
    file: path=/home/production state=directory

  - name: Copying Server Software
    git: repo=https://github.com/subodh-dharma/DevOps-M3.git dest=/home/production

  - name: Installing Server Software
    shell: npm --prefix /home/production install

  #- name: Clear Server data from Redis
  #  raw: node /home/production/main clearRedis

  - name: Stop all forever processes
    raw: forever stopall

  - name: Starting Web Server
    command: su ubuntu -c "forever start /home/production/main.js"

  - name: Install nginx
    apt: pkg=nginx state=installed update_cache=yes

  - name: Copy nginx configuration
    template: src=default dest=/etc/nginx/sites-available/default

  - name: Restart nginx
    service: name=nginx state=restarted

  - name: Allow nginx traffic through firewall
    ufw: rule=allow name='Nginx Full'

  #- name: Starting Request Monitoring services
  #  raw: su ubuntu -c "forever start /home/production/monitor_requests.js"

  #- name: Starting Memory Monitoring services
  #  raw: su ubuntu -c "forever start /home/production/monitor_memory.js"
